# Generated by Django 6.0.3 on 2026-04-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_game_delete_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_uuid',
        ),
        migrations.AddField(
            model_name='game',
            name='mode_formula',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
