# Generated by Django 6.0.3 on 2026-04-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='mode_formula',
            field=models.CharField(max_length=255),
        ),
    ]
